apiVersion: v1
kind: Service
metadata:
  name: tufts-acled
  labels:
    app: tufts-acled
spec:
  loadBalancerIP: 10.108.25.37
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tufts-acled
---
apiVersion: v1
kind: Pod
metadata:
  name: tufts-acled
  labels:
    app: tufts-acled
spec:
  restartPolicy: Always
  containers:
    # MIT-FEATURELABS TA2
    - name: mitfl-ta2
      #  - name: tamu-ta2
      #  - name: isi-ta2
      #  - name: cmu-ta2
      #  - name: nyu-ta2
      #  - name: stanford-ta2
      #  - name: ucb-ta2
      imagePullPolicy: Always
      image: registry.datadrivendiscovery.org/jkanter/mit-fl-ta2:stable
      # port 50051
      #    image: registry.datadrivendiscovery.org/ta3-submissions-summer/ta3-tufts/tamu:ta2
      # port 45042
      #    image: registry.datadrivendiscovery.org/ta3-submissions-summer/ta3-tufts/isi:ta2
      # port 45042
      #    image: registry.datadrivendiscovery.org/ta3-submissions-summer/ta3-tufts/cmu:ta2
      # port 45042
      #    image: registry.datadrivendiscovery.org/ta3-submissions-summer/ta3-tufts/nyu:ta2
      # port 45042
      #    image: registry.datadrivendiscovery.org/ta3-submissions-summer/ta3-tufts/stanford:ta2
      # port 50051
      #    image: registry.datadrivendiscovery.org/ta3-submissions-summer/ta3-tufts/ucb:ta2
      # port 45042
      volumeMounts:
        - name: static-data
          mountPath: /static-files
          readOnly: true
        # for UCB:
        #      - name: static-data
        #        mountPath: /volumes
        #        readOnly: true
        #      - name: shared-memory
        #        mountPath: /dev/shm
        - name: input-vol
          mountPath: /input
          readOnly: true
        - name: output-vol
          mountPath: /output
          readOnly: false
      ports:
        - containerPort: 50051
          hostPort: 50051
      #    - containerPort: 45042
      #      hostPort: 45042
      resources:
        requests:
          memory: 5Gi
          cpu: 2
      env:
        - name: D3MTIMEOUT
          value: "60"
        - name: D3MINPUTDIR
          value: /input
        - name: D3MOUTPUTDIR
          value: /output
        - name: D3MRUN
          value: ta2ta3
    # TUFTS TA3
    - name: tufts-ta3
      imagePullPolicy: Always
      image: registry.datadrivendiscovery.org/cliu/tuftsgtwiscta3
      command: [./ta3_search]
      args:
        #      - dataset:popularkids
        - dataset:__direct__
      volumeMounts:
        - name: input-vol
          mountPath: /input
          readOnly: true
        - name: output-vol
          mountPath: /output
          readOnly: false
      ports:
        - name: http
          containerPort: 8080
      resources:
        requests:
          # that's what we've been testing on:
          memory: 5Gi
          cpu: 1
      env:
        - name: TA2_PORT
          #      value: "45042"
          value: "50051"
  imagePullSecrets:
    - name: regcred-cl
  volumes:
    - name: static-data
      hostPath:
        path: /opt/static_files/
        type: Directory
    - name: input-vol
      hostPath:
        path: /opt/datasets/seed_datasets_current/LL0_acled_reduced
        type: Directory
    - name: output-vol
      persistentVolumeClaim:
        claimName: eval-output-pv-claim
# for UCB
#  - name: shared-memory
#    emptyDir:
#      medium: Memory
